export const siteConfig = {
  name: "CooprStudio",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://cooprstudio.com",
  description:
    "CooprStudio diseña, desarrolla y lanza sitios web modernos con SEO inicial, soporte y mantenimiento continuo para negocios que quieren crecer.",
  locale: "es_MX",
  email: "cooprstudio@gmail.com",
  keywords: [
    "diseño web",
    "desarrollo web",
    "páginas web",
    "landing pages",
    "SEO",
    "mantenimiento web",
    "diseño web en monterrey",
    "diseño web en mexico",
    "web modernas",
    "diseño web monterrey",
    "paginas web en monterrey",
    "CooprStudio",
    "SEO",
    "soporte web",
    "agencia de desarrollo web",
    "desarrollo web a medida",
    "diseño web personalizado",
    "desarrollo web profesional",
    "diseño web responsive",
    "desarrollo web con SEO",
    "soporte web en monterrey",
    "agencia de desarrollo web en monterrey",
    "desarrollo web a medida en monterrey",
    "diseño web personalizado en monterrey",
    "desarrollo web profesional en monterrey",
    "diseño web responsive en monterrey",
    "desarrollo web con SEO en monterrey",
    "agencia de diseño y desarrollo web",
    "agencia de diseño y desarrollo web en monterrey",
    "agencia de diseño y desarrollo web en mexico",
    "agencia de diseño web",
    "agencia de diseño web en monterrey",
    "agencia de diseño web en mexico",
    "diseño web profesional",
    "diseño web profesional en monterrey",
    "diseño web profesional en mexico",
    "desarrollo web profesional",
    "desarrollo web profesional en monterrey",
    "desarrollo web profesional en mexico",
  ],
};

export function absoluteUrl(path = "/") {
  return new URL(path, siteConfig.url).toString();
}
